# Generated by Django 4.2.4 on 2023-08-31 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowandreturn',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrows', to='book.book'),
        ),
        migrations.AddField(
            model_name='borrowandreturn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service.borrowandreturn',),
            managers=[
                ('borrowManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service.wishlist',),
            managers=[
                ('notificationManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service.borrowandreturn',),
            managers=[
                ('reminderManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service.wishlist',),
            managers=[
                ('reservationManger', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service.borrowandreturn',),
            managers=[
                ('returnManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('book', 'user'), name='already in wishlist'),
        ),
        migrations.AddConstraint(
            model_name='borrowandreturn',
            constraint=models.UniqueConstraint(fields=('book', 'user'), name='already borrowed'),
        ),
    ]
