# Generated by Django 4.2.4 on 2023-09-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_borrowandreturn_accepted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wishlist',
            managers=[
            ],
        ),
    ]
