# Generated by Django 4.2.4 on 2023-09-03 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_alter_book_author_alter_book_genre_delete_author_and_more'),
        ('service', '0004_alter_wishlist_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wishlists', to='book.book'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wishlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
