# Generated by Django 4.2.4 on 2023-09-18 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0007_alter_book_creator'),
        ('service', '0009_alter_borrowandreturn_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowandreturn',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='book.book'),
        ),
        migrations.AlterField(
            model_name='borrowandreturn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
