# Generated by Django 4.2.4 on 2023-09-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_creation_date_book_creator_book_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
