# Generated by Django 4.2.4 on 2023-09-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. ', verbose_name='Admin status'),
        ),
    ]
